name: quizzler_final
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - docs/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf

    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf

    - family: Roboto Slab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf




