// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASq940UULvMlt-yOr2wIVJTC6Jz_SaWdA',
    appId: '1:701573350224:web:99bfdb416d09c7bc9e2255',
    messagingSenderId: '701573350224',
    projectId: 'quizzler-flutter-75dac',
    authDomain: 'quizzler-flutter-75dac.firebaseapp.com',
    storageBucket: 'quizzler-flutter-75dac.firebasestorage.app',
    measurementId: 'G-60GNJDP1FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSVdjIVnHX3nZEGbloZjuzXLbpYQV0n4g',
    appId: '1:701573350224:android:56c639f8ad9d25f19e2255',
    messagingSenderId: '701573350224',
    projectId: 'quizzler-flutter-75dac',
    storageBucket: 'quizzler-flutter-75dac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP-8s93qUxNngphM_FKbBFfww9uk1C_UA',
    appId: '1:701573350224:ios:5d874e7f168c8caf9e2255',
    messagingSenderId: '701573350224',
    projectId: 'quizzler-flutter-75dac',
    storageBucket: 'quizzler-flutter-75dac.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP-8s93qUxNngphM_FKbBFfww9uk1C_UA',
    appId: '1:701573350224:ios:5d874e7f168c8caf9e2255',
    messagingSenderId: '701573350224',
    projectId: 'quizzler-flutter-75dac',
    storageBucket: 'quizzler-flutter-75dac.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASq940UULvMlt-yOr2wIVJTC6Jz_SaWdA',
    appId: '1:701573350224:web:6ae7707f00b0f8479e2255',
    messagingSenderId: '701573350224',
    projectId: 'quizzler-flutter-75dac',
    authDomain: 'quizzler-flutter-75dac.firebaseapp.com',
    storageBucket: 'quizzler-flutter-75dac.firebasestorage.app',
    measurementId: 'G-SBX7NB1MR3',
  );

}